//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#pragma once


namespace winrt::Home_Assistant_XAML::implementation
{
    using IInspectable = ::winrt::Windows::Foundation::IInspectable;

    template <typename D, typename ... I>
    struct MainWindowT : public ::winrt::Home_Assistant_XAML::implementation::MainWindow_base<D,
        ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,
        I...>
    {
        using base_type = typename MainWindowT::base_type;
        using base_type::base_type;
        using class_type = typename MainWindowT::class_type;

        void InitializeComponent();
        virtual void Connect(int32_t connectionId, IInspectable const& target);
        virtual ::winrt::Microsoft::UI::Xaml::Markup::IComponentConnector GetBindingConnector(int32_t connectionId, IInspectable const& target);
        void UnloadObject(::winrt::Microsoft::UI::Xaml::DependencyObject const& dependencyObject);
        void DisconnectUnloadedObject(int32_t connectionId);

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock resultField()
        {
            return _resultField;
        }
        void resultField(::winrt::Microsoft::UI::Xaml::Controls::TextBlock value)
        {
            _resultField = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox firstNumberField()
        {
            return _firstNumberField;
        }
        void firstNumberField(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _firstNumberField = value;
        }

        ::winrt::Microsoft::UI::Xaml::Controls::TextBox secondNumberField()
        {
            return _secondNumberField;
        }
        void secondNumberField(::winrt::Microsoft::UI::Xaml::Controls::TextBox value)
        {
            _secondNumberField = value;
        }
        
    protected:
        bool _contentLoaded{false};

    private:
        struct MainWindow_obj1_Bindings;

        ::winrt::Microsoft::UI::Xaml::Controls::TextBlock _resultField{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _firstNumberField{nullptr};
        ::winrt::Microsoft::UI::Xaml::Controls::TextBox _secondNumberField{nullptr};
    };
}

