// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

void* winrt_make_Home_Assistant_XAML_XamlMetaDataProvider()
{
    return winrt::detach_abi(winrt::make<winrt::Home_Assistant_XAML::factory_implementation::XamlMetaDataProvider>());
}
WINRT_EXPORT namespace winrt::Home_Assistant_XAML
{
    XamlMetaDataProvider::XamlMetaDataProvider() :
        XamlMetaDataProvider(make<Home_Assistant_XAML::implementation::XamlMetaDataProvider>())
    {
    }
}
