// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220929.3

#pragma once
#ifndef WINRT_Home_Assistant_XAML_0_H
#define WINRT_Home_Assistant_XAML_0_H
WINRT_EXPORT namespace winrt::Microsoft::UI::Xaml::Markup
{
    struct IXamlMetadataProvider;
}
WINRT_EXPORT namespace winrt::Home_Assistant_XAML
{
    struct IMainWindow;
    struct MainWindow;
    struct XamlMetaDataProvider;
}
namespace winrt::impl
{
    template <> struct category<winrt::Home_Assistant_XAML::IMainWindow>{ using type = interface_category; };
    template <> struct category<winrt::Home_Assistant_XAML::MainWindow>{ using type = class_category; };
    template <> struct category<winrt::Home_Assistant_XAML::XamlMetaDataProvider>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::Home_Assistant_XAML::MainWindow> = L"Home_Assistant_XAML.MainWindow";
    template <> inline constexpr auto& name_v<winrt::Home_Assistant_XAML::XamlMetaDataProvider> = L"Home_Assistant_XAML.XamlMetaDataProvider";
    template <> inline constexpr auto& name_v<winrt::Home_Assistant_XAML::IMainWindow> = L"Home_Assistant_XAML.IMainWindow";
    template <> inline constexpr guid guid_v<winrt::Home_Assistant_XAML::IMainWindow>{ 0xBB092775,0x3B50,0x58B6,{ 0x9A,0xA3,0xD1,0x4C,0xCD,0xE2,0xBF,0xF1 } }; // BB092775-3B50-58B6-9AA3-D14CCDE2BFF1
    template <> struct default_interface<winrt::Home_Assistant_XAML::MainWindow>{ using type = winrt::Home_Assistant_XAML::IMainWindow; };
    template <> struct default_interface<winrt::Home_Assistant_XAML::XamlMetaDataProvider>{ using type = winrt::Microsoft::UI::Xaml::Markup::IXamlMetadataProvider; };
    template <> struct abi<winrt::Home_Assistant_XAML::IMainWindow>
    {
        struct __declspec(novtable) type : inspectable_abi
        {
            virtual int32_t __stdcall get_MyProperty(int32_t*) noexcept = 0;
            virtual int32_t __stdcall put_MyProperty(int32_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_Home_Assistant_XAML_IMainWindow
    {
        [[nodiscard]] auto MyProperty() const;
        auto MyProperty(int32_t value) const;
    };
    template <> struct consume<winrt::Home_Assistant_XAML::IMainWindow>
    {
        template <typename D> using type = consume_Home_Assistant_XAML_IMainWindow<D>;
    };
}
#endif
